name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Add permissions block at the workflow level
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    env:
      ALLOW_UNRESOLVED_DEPENDENCIES: true
      USE_SYMLINKS: false
      USE_HARD_LINKS: false
      NODE_OPTIONS: --max_old_space_size=4096
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for release notes

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd src/renderer && npm ci && cd ../..

      - name: Generate Release Notes
        id: release_notes
        shell: bash
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, using all commits"
            RELEASE_NOTES=$(git log --pretty=format:"* %s (%h)" HEAD)
          else
            echo "Generating notes from $PREV_TAG to HEAD"
            RELEASE_NOTES=$(git log --pretty=format:"* %s (%h)" $PREV_TAG..HEAD)
          fi
          
          # Debug output (will be hidden in logs)
          echo "Generated release notes:"
          echo "$RELEASE_NOTES"
          
          # Escape for GitHub Actions
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          
          # Set output
          {
            echo "notes<<EOF"
            echo "$RELEASE_NOTES"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Package macOS app
        if: matrix.os == 'macos-latest'
        run: npm run package-app

      - name: Package Windows app
        if: matrix.os == 'windows-latest'
        run: npm run package-app

      - name: Prepare macOS artifacts
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p artifacts/macos
          # Move DMG and ZIP files to artifacts directory
          mv dist/*.dmg dist/*.zip artifacts/macos/ 2>/dev/null || true
          # Create a checksums file
          cd artifacts/macos && sha256sum * > checksums.txt

      - name: Prepare Windows artifacts
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p artifacts/windows
          # Move NSIS installer and portable exe to artifacts directory
          mv dist/*.exe artifacts/windows/ 2>/dev/null || true
          # Create a checksums file
          cd artifacts/windows && sha256sum * > checksums.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: artifacts/

      - name: Build and Publish
        shell: bash
        run: |
          echo "Starting build and publish..."
          # Debug: Show if we have release notes
          if [ -n "$RELEASE_NOTES" ]; then
            echo "Release notes are set (length: ${#RELEASE_NOTES})"
          else
            echo "Warning: No release notes available"
          fi
          npm run publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ steps.release_notes.outputs.notes }} 