name: Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
      NPM_CONFIG_FETCH_TIMEOUT: 300000
      NPM_CONFIG_FETCH_RETRIES: 5
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
      ELECTRON_VERSION: "28.1.0"
      ELECTRON_BUILDER_ARCH: "arm64"
      ELECTRON_BUILDER_PLATFORM: "darwin"
      ELECTRON_BUILDER_APP_DIR: "./"
      ELECTRON_BUILDER_BUILD_FROM_SOURCE: "false"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          cd src/renderer && npm install && cd ../..

      # macOS specific steps
      - name: Prepare macOS build environment
        if: matrix.os == 'macos-latest'
        run: |
          # Clean dist directory
          rm -rf dist/
          
          # Ensure all public assets have correct permissions
          chmod -R 644 build/icon.* || true
          chmod -R 644 src/renderer/public/* || true
          
          # Ensure build directory exists
          mkdir -p build
          
          # Copy public assets to build directory if they don't exist
          if [ ! -f build/icon.png ]; then
            cp src/renderer/public/logo512.png build/icon.png
          fi
          if [ ! -f build/icon.ico ]; then
            cp src/renderer/public/favicon.ico build/icon.ico
          fi

      - name: Build macOS app
        if: matrix.os == 'macos-latest'
        run: |
          cd src/renderer && npm run build && cd ../..
          npm run build-preload
          npm run prepare-flow-deps
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          ELECTRON_VERSION: "28.1.0"
          ELECTRON_BUILDER_ARCH: "arm64"
          ELECTRON_BUILDER_PLATFORM: "darwin"
          ELECTRON_BUILDER_APP_DIR: "./"
          ELECTRON_BUILDER_BUILD_FROM_SOURCE: "false"

      # Windows specific steps (using the working version)
      - name: Package Windows app
        if: matrix.os == 'windows-latest'
        run: npm run package-app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          ELECTRON_VERSION: "28.1.0"
          ELECTRON_BUILDER_ARCH: "x64"
          ELECTRON_BUILDER_PLATFORM: "win32"
          ELECTRON_BUILDER_APP_DIR: "./"
          ELECTRON_BUILDER_BUILD_FROM_SOURCE: "false"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aitomics-ui-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true 