name: Publish Release

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: *-artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: ${{ needs.build.outputs.release_notes }}
          files: |
            artifacts/macos/*.dmg
            artifacts/macos/*.zip
            artifacts/macos/checksums.txt
            artifacts/windows/*.exe
            artifacts/windows/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 