name: Release

on:
  push:
    tags:
      - 'v*'

# Add explicit permissions
permissions:
  contents: write  # Required for creating releases and uploading artifacts
  packages: write  # Required for publishing packages
  discussions: write  # Required for creating release discussions

# Add job timeout
jobs:
  package-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            src/renderer/package-lock.json
        timeout-minutes: 5

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund
          cd src/renderer && npm ci --no-audit --no-fund --no-progress && cd ../..
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build and package
        run: npm run package-app
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          ELECTRON_VERSION: "28.1.0"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: dist
          retention-days: 1

  package-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        timeout-minutes: 5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            src/renderer/package-lock.json
        timeout-minutes: 5

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund
          cd src/renderer && npm ci --no-audit --no-fund --no-progress && cd ../..
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build and package
        run: npm run package-app
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          ELECTRON_VERSION: "28.1.0"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist
          retention-days: 1

  release:
    needs: [package-macos, package-windows]
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-artifacts
          path: dist-mac

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
          path: dist-win

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-mac/*.dmg
            dist-mac/*.zip
            dist-win/*.exe
            dist-win/*.portable.exe
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 